# What are loops? and how to use them in Python? How many types of loops are there in Python? Let's discuss about them in this chapter.
# Loops are used to execute a block of code repeatedly until a certain condition is met.

# There are two types of loops in Python:
# 1. for loop
# 2. while loop

# Lets discuss about while loop. 
# The while loop is used to execute a block of code repeatedly as long as a certain condition is true. The syntax of while loop is:
# while condition:
#     # block of code

# Example of while loop:
i = 1
while i <= 5:
    print(i)
    i += 1

# In the above example, the condition i <= 5 is true, so the block of code inside the while loop will be executed and the value of i will be printed. The value of i will be incremented by 1 in each iteration until the condition becomes false.

# Lets discuss some more examples of while loop:
# Example of while loop with break statement:
i = 1
while i <= 5:
    print(i)
    if i == 3:
        break
    i += 1
    
# In the above example, the condition i <= 5 is true, so the block of code inside the while loop will be executed and the value of i will be printed. When the value of i becomes 3, the break statement will be executed and the loop will be terminated.

# Lets talk about for loop.
# The for loop is used to iterate over a sequence (such as a list, tuple, dictionary, set, or string) and execute a block of code for each item in the sequence. The syntax of for loop is:
# for item in sequence:
#     # block of code

# Example of for loop:
fruits = ["apple", "banana", "cherry"]
for fruit in fruits:
    print(fruit)
    
# In the above example, the for loop will iterate over each item in the fruits list and print the value of fruit in each iteration.

# Lets discuss some more examples of for loop:
# Example of for loop with range() function:
for i in range(5):
    print(i)

# In the above example, the for loop will iterate over a sequence of numbers generated by the range() function and print the value of i in each iteration. The range(5) function generates a sequence of numbers from 0 to 4.

# Example of for loop with break statement:
for i in range(5):
    print(i)
    if i == 3:
        break

# In the above example, the for loop will iterate over a sequence of numbers generated by the range() function and print the value of i in each iteration. When the value of i becomes 3, the break statement will be executed and the loop will be terminated.

# Thank you for reading this chapter. I hope you enjoyed it and learned something new about loops in Python. Happy coding!
# Follow me on linkedin: www.linkedin.com/in/abdulrehman2002